name: UltraV
version: '1.0.6-SNAPSHOT'
main: com.randomtikspeed.ultrav.UltraV
api-version: 1.18
author: RandomTikSpeed
commands:
  start:
    description: Start quests
    usage: /<command>
    permission: ultrav.start
  ultrav:
    description: UltraV Admin Panel
    usage: /<command>
    permission: ultrav.admin
  clearchat:
    description: Clears everyone's chat (250 lines)
    usage: /<command>
    permission: ultrav.admin
  store:
    description: Sends a link to the store
    usage: /<command>
  kfc:
    description: Gives you KFC (suggested by ShadowRexYT, only avaliable to ShadowRexYT)
    usage: /<command>
  hub:
  rules:
    description: Opens the rules GUI
    usage: /<command>